[package]
name = "rust-pong"
version = "0.1.0"
authors = ["Aditya Dhara <aditya1992@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tetra = "0.4"
